### ISSUE TITLE
Inference output

### ISSUE THREAD

**Issue by Junboooo** [House-Leo/RWSR-EDL#4]
NICE WORK!
I have a question about what is the output of model Inference, if IRx and iRy are only used for training. <br>

`
self.fake_H, self.out1, self.out2 = self.netG(self.var_L)
`<br>
In SRGAN_model.py 218 is still use self.fake_H to inference.

**Comment by House-Leo** [comment]
Sorry for the confusion.

According to the following codes in `RRDBNet_arch.py`
https://github.com/House-Leo/RWSR-EDL/blob/a184149f9432c725cffc05c2a6ba031286aa6bf5/codes/models/modules/RRDBNet_arch.py#L106-L108

The `self.fake_H, self.out1, self.out2` denotes the `out, out1, out2` respectively. 
`self.out1` and `self.out2` are only used for loss optimization in training, the final output is `self.fake_H`.

You can easily change the code 
`self.fake_H, self.out1, self.out2 = self.netG(self.var_L)`
to
`self.fake_H, _, _= self.netG(self.var_L)`.
It can also work well.

Thank you :)

**Comment by Junboooo** [comment]
Thank you very much for your detailed reply！
I have understood the output during inference is self.fake_H. But self.fake_H is consist by IRx(out1) and IRy(out2). In my perspective, the network inference still need to calculate IRx and IRy, which have calculate cost in inference. Self.out1 and self.out2 are not only used for training but also used for inference. I don't know if I understand correctly？

**Comment by House-Leo** [comment]
That's right.
 IRx(out1) and IRy(out2) always need to be calculated during forward processing.

**Comment by Junboooo** [comment]
Thx for patient reply!
